apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: om-mongo
  namespace: om
  labels:
    app: mongodb
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: om-parts
  namespace: om
  labels:
    app: backend
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: om-media
  namespace: om
  labels:
    app: backend
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: om-covers
  namespace: om
  labels:
    app: backend
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 704Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: om-redis
  namespace: om
  labels:
    app: backend
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 64Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: om-traefik
  namespace: om
  labels:
    app: traefik
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi