apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: duplicati
spec:
  destination:
    name: ''
    namespace: om
    server: 'https://kubernetes.default.svc'
  source:
    path: templates/kubernetes/duplicati
    repoURL: 'git@github.com:smartnexus/OrchestraManager'
    targetRevision: react_version
    directory:
      jsonnet:
        tlas: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true