apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  destination:
    name: ''
    namespace: om
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://helm.traefik.io/traefik'
    targetRevision: 10.20.0
    chart: traefik
    helm:
      values: |-
        ---
        additionalArguments:
          - --entrypoints.websecure.http.tls.certresolver=cloudflare
          - --entrypoints.websecure.http.tls.domains[0].main=k8s.orchestramanager.pw
          - --entrypoints.websecure.http.tls.domains[0].sans=*.k8s.orchestramanager.pw
          - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
          - --certificatesresolvers.cloudflare.acme.email=angelitoxd99@gmail.com
          - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
          - --certificatesresolvers.cloudflare.acme.storage=/data/acme.json
        ports:
          web:
            redirectTo: websecure
        env:
          - name: CF_API_EMAIL
            valueFrom:
              secretKeyRef:
                key: email
                name: cloudflare-api-credentials
          - name: CF_DNS_API_TOKEN
            valueFrom:
              secretKeyRef:
                key: dnsApiToken
                name: cloudflare-api-credentials
        ingressRoute:
          dashboard:
            enabled: false
        persistence:
          enabled: true
          name: data
          existingClaim: om-traefik
          accessMode: ReadWriteOnce
          size: 256Mi
          path: /data
        #   annotations: {
        #     "pv.beta.kubernetes.io/gid": "65532"
        #   }

        # # Fix for acme.json file being changed to 660 from 600
        # podSecurityContext: null
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true