apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: persistent-volumes
spec:
  destination:
    name: ''
    namespace: om
    server: 'https://kubernetes.default.svc'
  source:
    path: templates/kubernetes/shared-storage
    repoURL: 'git@github.com:smartnexus/OrchestraManager'
    targetRevision: react_version
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true