---
additionalArguments:
  - --entrypoints.websecure.http.tls.certresolver=cloudflare
  - --entrypoints.websecure.http.tls.domains[0].main=tfg.orchestramanager.pw
  - --entrypoints.websecure.http.tls.domains[0].sans=*.tfg.orchestramanager.pw
  - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
  - --certificatesresolvers.cloudflare.acme.email=angelitoxd99@gmail.com
  - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
  - --certificatesresolvers.cloudflare.acme.storage=/data/acme.json
ports:
  web:
    redirectTo: websecure
env:
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        key: email
        name: cloudflare-api-credentials
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        key: dnsApiToken
        name: cloudflare-api-credentials
ingressRoute:
  dashboard:
    enabled: false
resources:
  requests:
    cpu: "200m"
    memory: "200Mi"
  limits:
    cpu: "300m"
    memory: "300Mi"
deployment:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
metrics:
  prometheus:
    entryPoint: metrics
    addRoutersLabels: true
providers:
  kubernetesIngress:
    enabled: false
persistence:
  enabled: true
  name: data
  existingClaim: om-traefik
  accessMode: ReadWriteOnce
  size: 256Mi
  path: /data
#   annotations: {
#     "pv.beta.kubernetes.io/gid": "65532"
#   }

# # Fix for acme.json file being changed to 660 from 600
# podSecurityContext: null