version: '3'

services:
  redis:
    image: redis:alpine
    container_name: om_redis
    restart: always
    ports:
      - 6379

  mongo:
    image: mongo
    container_name: om_mongo
    restart: always
    ports:
      - 27017
    volumes: 
      - ./volumes/mongo/database:/data/db

  mongorestore:
    image: mongo-tools
    container_name: om_restore
    environment:
      - RESTORE_ENV=no
#      - WAIT_FOR=mongo:27017
    volumes:
      - ./volumes/mongo/backup:/backup
    depends_on:
      - mongo

  backend:
    image: orchestramanager.pw/app/backend
    container_name: om_backend
    environment: 
      - WAIT_FOR=mongo:27017
    ports:
      - 3000
    depends_on:
      - redis
      - mongo
    volumes:
      - ./volumes/parts:/app/parts
      - ./volumes/media:/app/media
      - ./volumes/images:/app/covers
      - ./volumes/mongo/backup:/app/backup
      - ./config:/app/config
  
  frontend:
    image: orchestramanager.pw/app/frontend
    container_name: om_frontend
    depends_on:
      - backend
    ports:
     - 80
